@startuml Use_Case

left to right direction

:user:
:customer_user:
:user: <|-- :customer_user:
:administrator:
:user: <|-- :administrator:
package sol_system {
    :user: --> (authenticate)
    :customer_user: --> (place orders)
    :customer_user: --> (track orders)

    :administrator: --> (change order status)
    :administrator: --> (update products catalog)
    (change order status) .. (update order status) : extends
    (place orders) .. (update order status) : extends
    (authenticate) .. (sign-up) : extends
    (authenticate) .. (log-in) : extends
}

@enduml