services:
  web:
    build: .
    environment: 
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: >
      sh -c "
        rm -rf /app/__pycache__
        flask run --host=0.0.0.0 --debug"
  redis:
    image: "redis:latest"
